export const data = [
  {
    id: 1,
    name: "KIỂM SOÁT CHẤT LƯỢNG",
    children: [
      {
        id: 1,
        name: "Chờ tôi xử lý",
        icon: null,
        url: "/waiting_approval",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 2,
        name: "Đang xử lý",
        icon: null,
        url: "/in_progress",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 3,
        name: "Soạn thảo",
        icon: null,
        url: "/drafting",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 4,
        name: "Tất cả",
        icon: null,
        url: "/all_plans",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
    ],
  },
  {
    id: 2,
    name: "QUẢN TRỊ",
    children: [
      {
        id: 5,
        name: "Dẫn hướng",
        icon: null,
        url: "/menu",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 6,
        name: "Vai trò",
        icon: null,
        url: "/role",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 7,
        name: "Phân quyền",
        icon: null,
        url: "/privilege",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 8,
        name: "Cài đặt",
        icon: null,
        url: "/setting",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 9,
        name: "Quy trình mẫu",
        icon: null,
        url: "/workflow",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 10,
        name: "Mẫu ký số",
        icon: null,
        url: "/sign_document",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 11,
        name: "Tình trạng",
        icon: null,
        url: "/status",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 12,
        name: "Hành động",
        icon: null,
        url: "/action",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 13,
        name: "Bộ mẫu",
        icon: null,
        url: "/sample",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 14,
        name: "Phân xưởng",
        icon: null,
        url: "/workshop",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 15,
        name: "Phòng thử nghiệm",
        icon: null,
        url: "/laboratory",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 16,
        name: "Phương pháp thử nghiệm",
        icon: null,
        url: "/testing_method",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 17,
        name: "Tên mẫu",
        icon: null,
        url: "/sample_name",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 18,
        name: "Mục đích",
        icon: null,
        url: "/purpose",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 19,
        name: "Quy trình lấy mẫu",
        icon: null,
        url: "/sampling_procedure",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 20,
        name: "Điểm lấy mẫu",
        icon: null,
        url: "/sampling_point",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 21,
        name: "Chỉ tiêu kiểm soát",
        icon: null,
        url: "/control_criteria",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
      {
        id: 22,
        name: "Mức độ khẩn cấp",
        icon: null,
        url: "/critical",
        isCount: 0,
        roles: "",
        isDeleted: false,
      },
    ],
  },
];
