<template>
  <div class="fullFrame">
    <div class="departmentTreeFrame">
      <div>
        <div class="leftFrame">
          <DxAutocomplete
            :input-attr="{
              placeholder: 'Tìm kiếm phòng ban',
              class: 'search-input',
            }"
            :show-clear-button="true"
            class="searchInput"
            ><template #prefix>
              <span class="dx-icon dx-icon-search"></span>
            </template>
          </DxAutocomplete>
        </div>
        <div
          id="department-jstree"
          ref="departmentTree"
          class="departmentTree"
        ></div>
      </div>
      <div class="contentFrame">
        <div class="contentTitle">
          <p class="contentTitleText">Vai trò</p>
        </div>
        <DxDataGrid
          id="dataGrid"
          :show-borders="isShowBorders"
          :row-alternation-enabled="isRowAlternationEnabled"
          :data-source="gridData"
          @selection-changed="selectDepartments"
          :show-row-lines="isShowRowLines"
          :show-column-lines="isShowColumnLines"
          class="table"
        >
          <DxColumn data-field="Vai trò" width="100px"> </DxColumn>
          <DxColumn data-field="Người dùng"> </DxColumn>
        </DxDataGrid>
      </div>
    </div>
  </div>
</template>

<script>
// Import jsTree
import "jstree/dist/themes/default/style.min.css";
import $ from "jquery";
import "jstree";

import { DxDataGrid, DxColumn } from "devextreme-vue/data-grid";
import DxAutocomplete from "devextreme-vue/autocomplete";

export default {
  name: "DepartmentTree",
  components: {
    DxAutocomplete,
    DxDataGrid,
    DxColumn,
  },
  data() {
    return {
      gridData: [],
      isShowBorders: true,
      isRowAlternationEnabled: true,
      isShowRowLines: true,
      isShowColumnLines: true,
    };
  },
  mounted() {
    this.initTree();
  },
  methods: {
    initTree() {
      // Dữ liệu cây tổ chức cơ bản
      const data = [
        {
          parentItem: null,
          id: "2d85c507-c7f8-426c-9022-de6ef01e5d41",
          text: "Công Ty Cổ Phần Lọc hoá dầu Bình Sơn",
          node_text: null,
          icon: null,
          state: null,
          children: [
            {
              parentItem: null,
              id: "b5896e79-def5-4fa7-a780-8f1f3a59e1a5",
              text: "Hội Đồng Quản Trị",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "69259c33-ead3-4c59-a955-9c2300e8061e",
              text: "Ban Tổng Giám đốc",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "53d8a7b3-fa25-44da-9c7f-8523215e716f",
              text: "Ban Tài chính kế toán",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "633973d9-ad4c-4c97-9a0a-423af7a2327b",
                  text: "Phòng Kế toán",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "594a2e9f-9feb-407f-8cd1-2e8431d12f04",
                      text: "Tổ Kế toán chi phí hàng hóa (Dầu thô, XDCB, chi phí quản lý)",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "f153a81a-6a14-4dc0-ab42-c4e28e131b3c",
                      text: "Tổ Kế toán Chi phí dịch vụ ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "75d0eeb8-9161-4df4-81e4-255b6a6b3177",
                      text: "Tổ Kế toán tổng hợp ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a1b804bb-191f-429c-8adc-d6ef29bf6d3f",
                      text: "Tổ Kiểm toán nội bộ - Thuế",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "158b145b-1850-4da3-8007-c1231383186e",
                  text: "Phòng Tài chính",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "121650f1-9f86-4b57-bdc2-4d06c90abcba",
                      text: "Tổ Tài chính Tín dụng",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "794260af-6fab-4bc4-a1bc-a1041d46c0bc",
                      text: "Tổ Đầu tư Tài chính",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "1e11e793-fa44-4bec-9d40-17e8d64635af",
                      text: "Tổ Tài chính Quản trị",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "2277fb02-92cc-4c55-86f9-525df6dfb271",
              text: "Ban Quản trị nguồn lực",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "97066dca-b5fd-49e9-b428-9c3b6bb3d987",
                  text: "Phòng Lao động tiền lương",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "98ea477b-43b1-4ff3-82f8-80853bfc95d8",
                      text: "Tổ tiền lương",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "fc7f00bf-fbf3-466e-a36f-8a0fea542ffc",
                      text: "Tổ Quản lý lao động",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "59433078-56a9-418e-a473-b4d0bc6b3a2a",
                      text: "Tổ Bảo hiểm và chế độ chính sách",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "9f5a5f63-4b1a-4513-9427-fc2b00ca14f7",
                  text: "Phòng Đảng - Đoàn thể",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: false,
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "14cc7753-250c-4522-aba8-62e181f4a3ed",
                  text: "Phòng Tổ chức nhân sự",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "deb21b99-781f-479e-8b75-6a7431828815",
                      text: "Tổ KPI và TĐKT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "42afcae0-60b1-465d-a4d7-eaeb20261784",
                      text: "Tổ nhân sự",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "38c38e3a-649a-4d93-ac89-1413c3744c88",
                  text: "Phòng đào tạo và phát triển nguồn nhân lực",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "f4ebb563-0a6f-4b42-8f3e-ce749af5c291",
                      text: "Tổ đào tạo khối CMNV và KDTM",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "e77c672b-b5c6-481e-adba-69103b739f74",
                      text: "Tổ đánh giá năng lực, điều phối chung, ĐTKN",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "1b936c39-ee5b-4a7d-ab32-f297261889eb",
                      text: "Tổ đào tạo khối Sản xuất",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "afceb006-0d54-4cbe-a11e-c7d529305058",
              text: "Văn phòng",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "53024713-6711-43c7-9a25-d7866728a5c4",
                  text: "Phòng Quản trị",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "31bb13a1-fe3c-47a4-be96-5cc2c2fc8971",
                      text: "Tổ KH & Quản lý tài sản",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "9fcb5739-2a32-4b39-9935-bd15c6b4493f",
                      text: "Tổ Dịch vụ hậu cần",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "ea9b2112-5909-41d4-ae4f-ad41401ea213",
                      text: "Tổ quản trị",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "5561a3c0-f753-490d-8b0f-0b833151d01d",
                      text: "Đội xe",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "6efc602f-34e0-48df-8dee-c656a5fcef67",
                  text: "Phòng Hành chính",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "c5d9f535-f47d-4956-97b7-77fb87c78628",
                      text: "Tổ Văn thư",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "74025cb0-eb8f-438e-a00d-d9039bf029ad",
                      text: "Tổ Lưu Trữ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "57510c6f-fcf0-43f2-af53-4db942a08ce5",
                      text: "Tổ Truyền thông",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "5629eb32-4098-4325-9379-f04fbb2ad9fa",
                      text: "Nhóm biệt phái Hà nội",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "112ccd5b-de0b-4b16-8dd2-7c6c436b565f",
                      text: "Tổ Thư ký",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "cc55896e-7097-4dd9-bbbf-bd188983525a",
              text: "Ban Kinh doanh",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "a1d61f12-4ce5-42a3-ad90-d9e9983dd229",
                  text: "Phòng Kinh doanh sản phẩm",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "f1d95cf7-3c4d-4b6e-9b27-d12b33c4370f",
                      text: "Tổ Kinh doanh sản phẩm khác",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "9460212d-2d6a-435a-98a4-6faf498d7e1e",
                      text: "Tổ Kinh doanh sản phẩm xăng dầu",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "0074daf3-4bb6-42fd-bdbb-6e7316672899",
                  text: "Phòng Kinh doanh dầu thô",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "59301fce-698f-4f8b-914c-8a37e3ca3c62",
                      text: "Tổ kinh doanh dầu thô",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "e72277f7-7c5e-4d38-b02f-8b0ac2aa3751",
                      text: "Tổ Logistic",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "86e55b3e-de86-4224-84bd-610160bfa6cc",
                  text: "Phòng Marketing",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "5b23e7ec-75a9-4076-9e87-18da8810d729",
                      text: "Tổ Nghiên cứu phát triển kinh doanh",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "c2bf431b-aa76-48ae-a603-514fcbc57c33",
                      text: "Tổ Nghiên cứu thị trường",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "e8cddd90-29a9-4f50-9aff-e5a192850959",
              text: "Ban Pháp chế và Quản trị rủi ro",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "df80cbb7-9a1f-42e9-bae7-8e85361841d7",
                  text: "Phòng Pháp chế và hệ thống quản lý",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "4cafcf74-ad04-49ac-b024-cdf0f0ef0e75",
                      text: "Tổ Pháp chế",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "37b44bfe-9a97-4ece-a10d-036ba8c1862e",
                      text: "Tổ QLHT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "e8d6e73a-c19a-4ab1-8f30-280a3a9f0558",
                      text: "Tổ rủi ro, hợp đồng",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a295aa65-31b9-4360-b0a7-b89908a4404a",
                      text: "Văn Thư, Tổng hợp",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "6f66d5e8-d3d3-4279-9cdd-5e20c65d8ebd",
                  text: "Phòng Quản trị rủi ro và bảo hiểm",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "035be2a0-51a4-48e1-ae3e-14f1430973cd",
                      text: "Tổ bảo hiểm",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "6f623712-e8c0-4999-aa78-d3ad03579770",
              text: "Ban An toàn môi trường",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "432a8c0d-434e-4ed0-ad29-36c7a2965d01",
                  text: "Phòng Môi trường sức khỏe",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "fe5e15ec-81bb-4d74-adfc-5b1875e00139",
                      text: "Trạm Y tế",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "ca3066cf-0d75-48e0-a46f-a6103c4bcd19",
                      text: "Tổ Quản lý môi trường",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "12c66ab3-e562-4912-87f0-99f2c120f7dc",
                      text: "Tổ Quản lý chất thải - Vệ sinh công trường",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "f3cd03a9-8aaa-4f59-96dc-46b8928cd5f5",
                      text: "Tổ Bảo hộ lao động",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "7b6664ee-efd8-46ee-af9b-b8c151e4e0d7",
                  text: "Phòng An toàn PCCC",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "8d297501-8de6-4f54-8baf-65a535c97f51",
                      text: "Lái xe chữa cháy",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "abffe3c1-0655-458f-b4d1-318a42134778",
                      text: "Tổ giám sát ứng phó tình huống khẩn cấp",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a3c549a7-32a7-4572-af6d-b329ec8297dc",
                      text: "Công nhân PCCC",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "089a861a-9d2a-413a-8eff-53b07730094d",
                      text: "Tổ giám sát an toàn Offiste, Jetty & SPM",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "3fbebc03-5278-46ec-9b5d-b5898a7fccb9",
                      text: "Tổ giám sát an toàn khu vực công nghệ (P1)",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "9e75a645-6f3d-4a5a-b042-91883c141626",
                      text: "Trưởng ca PCCC ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "c3ab9c4a-146b-4779-afbc-b1eb142cc996",
                  text: "Phòng Quản trị an ninh an toàn",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "1a41581c-3f05-4c01-bf67-36cf86693c2c",
                      text: "Tổ tuyên truyền và huấn luyện ATSKMT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a0f6b972-9237-4240-a420-61f3cf067ac6",
                      text: "Tổ Quản lý hệ thống an ninh an toàn",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "1697fe2f-fa5d-487f-9576-85df3dc1621b",
                      text: "Tổ Triển khai công tác an ninh",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "c7fbe38f-e75d-4b54-ae8c-af53ee9dfb86",
                      text: "Tổ quản trị hệ thống ATSKMT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "8df17f62-7686-4ab7-8d64-e0468f65dd8d",
              text: "Ban Thương mại dịch vụ",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "d48e5e61-c37c-4329-ace3-1ee72d376ce1",
                  text: "Phòng Mua sắm vật tư",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "ae9a409f-2661-4db3-9d75-156e08617dc6",
                      text: "Tổ giao nhận (Logistics)",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "f769e365-1118-484a-aa4e-759c89581b4e",
                      text: "Tổ Mua sắm phụ tùng vật tư cho thiết bị C&I, Điện và vật tư tiêu hao",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "749a38a2-58a3-4111-be26-dff345abb82e",
                      text: "Tổ Mua sắm phụ tùng vật tư cho thiết bị cho thiết bị tĩnh và quay",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "68fd1f32-29fc-45be-bc03-f71fa18364b7",
                  text: "Phòng mua sắm hóa phẩm xúc tác và dịch vụ",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "a6d3d557-9218-4bcb-8ecd-7e65a68140dc",
                      text: "Tổ Dịch vụ kỹ thuật",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "8066f7d9-0b7f-4371-af18-1611807c7103",
                      text: "Tổ mua sắm phục vụ Quản lý điều hành",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "e00ffa27-182a-461e-92b6-4710d5989141",
                      text: "Tổ Tổng hợp QLHT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "67d4ee42-11a2-4760-b8ec-a647393b905e",
                      text: "Tổ HPXT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "ba60fe94-191c-45fd-95bf-84aec427056b",
              text: "Ban Nghiên cứu và phát triển",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "2f35dbdb-5de0-47cb-8c18-1bb1b3871255",
                  text: "Phòng Nghiên cứu khoa học và tối ưu hóa",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "21a8fd4e-6d2c-4f9e-9e7e-bed4fc8fc5fd",
                      text: "Tổ quản lý năng lượng và tổn thất",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "3b15300d-d919-4891-9719-e70ad692c74a",
                      text: "Tổ Tối ưu hóa vận hành",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "d26b9597-6313-4e34-8d4e-365f992bebda",
                      text: "Tổ Nghiên cứu khoa học",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "72d8c198-b978-486c-90f5-7770d2da1ec6",
                  text: "Phòng Kỹ thuật công nghệ",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "f73455dc-0b53-4ab4-a613-1a6655d3e73b",
                      text: "Tổ công nghệ khu vực ngoại vi",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "996bde6a-de80-46f3-8a2c-c8836e2b3e02",
                      text: "Tổ công nghệ cụm phân xưởng 3 & ETP",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a56935dc-351f-43e5-a8e3-b9b726dc74b5",
                      text: "Tổ công nghệ khu vực phụ trợ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "be615b60-c84b-4a36-b31e-acc3f06aa8cf",
                      text: "Tổ công nghệ cụm phân xưởng 1",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "9d24f4b3-fbb2-44db-9f02-72a8604a2781",
                      text: "Tổ công nghệ PP",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "d0aaf7ce-120e-4193-b48d-fb3b903dcf34",
                      text: "Tổ công nghệ cụm phân xưởng 2",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "0a6fe4f5-067f-4187-adbc-076423072cd6",
                  text: "Phòng Tự động hóa và công nghệ thông tin",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "17923620-7889-4753-b656-fbbfa7ae9e28",
                      text: "Tổ hệ thống điều khiển",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "2687646b-b666-4c8f-b03b-a3122b49b1e2",
                      text: "Tổ hệ thống tối ưu hóa",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "b05611d4-0cbb-4246-82fe-ef8dd88fa53f",
                  text: "Phòng Thiết kế và an toàn công nghệ",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "d834f44d-b134-4237-8bec-96584eac8928",
                      text: "Tổ quản lý an toàn công nghệ ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "df8c0081-1402-46ee-9def-4c8f1786ceda",
                      text: "Tổ thiết kế điện, cơ khí, xây dựng và tự động hóa",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "7eecb249-5c38-49cf-ba49-11ecfe8a856b",
                      text: "Tổ thiết kế công nghệ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "37ecad20-420a-4504-b817-d089be0dc5d7",
                  text: "Nhóm tổng hợp, thư ký",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: false,
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "435a1e89-ed74-4e16-93bd-f7c810c89069",
              text: "Ban Vận hành sản xuất",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "8b13ccd2-5a95-48cf-a430-2230126fdbae",
                  text: "Bộ phận điều hành sản xuất",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: false,
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "8f7361e7-8ec2-42e2-8a52-30a6e2fb2b5d",
                  text: "Phòng VHSX cụm phân xưởng sản xuất hạt nhựa",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "faefa4b3-1c60-4913-b498-10aad8c4afac",
                      text: "Khu vực Polypropylen",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "e15f5a88-07b2-4671-996f-95b88bc06317",
                      text: "Đội xe",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "cddbfc3a-6d9e-47a8-ad44-9a871dd3add5",
                  text: "Phòng VHSX cụm phân xưởng Điện hơi",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "0e9a59ba-2f3d-46ea-8b8d-8dcc23bcb714",
                      text: "Khu vực Boiler/STG - POWER PLANT",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "62dca617-376b-4928-a438-737f545b84a7",
                      text: "Khu vực Cold Utility",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "27e4d6a4-6ac3-4b95-ba15-e013d88b4639",
                  text: "Phòng VHSX hệ thống kho và Nhập Xuất",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "1028b8b1-d75a-49af-a803-1fc72e9df181",
                      text: "Khu vực P3/Jetty",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "9af6fcca-5c7f-4960-8e24-cc262e270d15",
                      text: "Khu vực Offsite - CRUDE/INTERMEDIATE TANKS",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "b93c3c14-ef65-42e6-badb-b7a5c6ceccfc",
                  text: "Phòng VHSX cụm phân xưởng Xử lý lưu huỳnh",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "5815033f-55b9-468c-81e7-2bf8d38f9483",
                      text: "Khu vực 3/ETP - SWS/ARU/CNU SRU/LCO/ETP",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "3010dbcc-2398-465c-89db-841b3228d6fd",
                  text: "Phòng VHSX cụm phân xưởng Chưng cất dầu thô",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "97a427b5-42a7-4994-996c-b8c34ade6729",
                      text: "Khu vực 1B - CDU/KTU",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "523cdc39-130a-4891-8f39-d2762c542708",
                      text: "Khu vực 1A - NHT/CCR/ISOM",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "7077944b-c561-473e-af3c-fc1cd6b43c94",
                  text: "Phòng VHSX cụm phân xưởng RFCC",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "ea7747d2-5283-4663-ac20-b52c736cc0d7",
                      text: "Khu vực 2 - RFCC/NTU/LTU/PRU",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "787eb7d6-cfe8-4d10-b64e-b85bfede861d",
              text: "Ban Quản lý chất lượng",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "03108d09-f1ff-4430-ba2c-cf77e68014ef",
                  text: "Phòng Đảm bảo chất lượng và kỹ thuật phân tích",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "1a94e30e-0ce9-49c3-91ee-78d96a0a65d6",
                      text: "Tổ Kế hoạch & ISO",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a8e9c856-3e20-411a-a922-b56391cee75b",
                      text: "Tổ ĐBCL Nguyên vật liệu",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "54deac6d-d992-4939-9fc9-03ffdd992af2",
                      text: "Tổ ĐBCL Sản phẩm",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "96b0cf3c-7615-4ef8-a120-8ea714622ef1",
                      text: "Tổ Crude oil Assay",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "b93cb610-bae4-434b-91fa-693713cd5bfa",
                  text: "Phòng Kiểm soát chất lượng",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "12bdc000-a74e-4755-a89e-ba86d9fdbbd8",
                      text: "Tổ Khí và Sắc ký khí",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "3c1f0b5a-bf5d-457d-b16f-1638e3a1b646",
                      text: "Tổ Sản phẩm",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "5ab8b283-8a84-4f49-8595-cb1f690fc2bd",
                      text: "Đi ca",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "73020a10-b5ab-4cc1-bef3-6dba9af90437",
                      text: "Tổ Công nghệ",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "b475b13d-8413-4783-b79b-2d3fd88344f6",
                      text: "Tổ Nguyên liệu",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "7cef7b86-f15f-454b-a3f6-40b3801d9918",
                      text: "Tổ Nước",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "50544a28-c041-43f3-8868-fe9ca79f0906",
                      text: "Tổ Nguyên tố",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "2ddf4c46-896d-4025-9b36-725de1d91bf2",
              text: "Ban Công nghệ thông tin",
              node_text: null,
              icon: null,
              state: null,
              children: [
                {
                  parentItem: null,
                  id: "8914d2a4-af09-4e1a-9787-341808d321c2",
                  text: "Phòng Quản trị hệ thống và hỗ trợ người dùng",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "32b6d18f-1f57-4434-9a83-f11e074664e2",
                      text: "Tổ Quản lý, vận hành, bảo dưỡng hệ thống",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "ef603110-5a84-4ddf-86a2-81a68a04cc77",
                      text: "Tổ Hỗ trợ người dùng",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "1ac9a1e9-987b-4172-8d79-145fb665368c",
                      text: "Tổ Quản lý, quản trị các ứng dụng",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
                {
                  parentItem: null,
                  id: "bf88f94b-9f5c-4875-9fde-0316268bc91c",
                  text: "Phòng Phát triển giải pháp",
                  node_text: null,
                  icon: null,
                  state: null,
                  children: [
                    {
                      parentItem: null,
                      id: "02eafc2f-5f86-4095-a556-487d2b59a1ed",
                      text: "Tổ cơ sở hạ tầng, hệ thống lõi, an ninh bảo mật",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "a44c26a2-865d-406b-9b32-a5776b46f44e",
                      text: "Tổ EAM và MIS",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                    {
                      parentItem: null,
                      id: "fd3bf7a8-a806-4577-a152-cc1ace10c6ac",
                      text: "Tổ ERP, e-office và quản trị Công ty",
                      node_text: null,
                      icon: null,
                      state: null,
                      children: false,
                      li_attr: null,
                      a_attr: null,
                      left_paramvalues: null,
                      left_iscount: false,
                      left_paramnames: null,
                    },
                  ],
                  li_attr: null,
                  a_attr: null,
                  left_paramvalues: null,
                  left_iscount: false,
                  left_paramnames: null,
                },
              ],
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "0ea5eda2-7611-47c5-98d4-a538c27f2ad8",
              text: "Ban Kiểm soát Nội bộ",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "71553714-e2f8-4792-a4b3-c20e6ec46527",
              text: "Văn phòng Hội đồng quản trị",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
          ],
          li_attr: null,
          a_attr: null,
          left_paramvalues: null,
          left_iscount: false,
          left_paramnames: null,
        },
        {
          parentItem: null,
          id: "bfaa6c4e-fe8e-441c-b886-6b9cd36acdfb",
          text: "Công ty CP công nghệ BTEC Chi nhánh Hà Nội",
          node_text: null,
          icon: null,
          state: null,
          children: [
            {
              parentItem: null,
              id: "7f06fc1c-faad-47a9-b472-750e3e7f3d19",
              text: "HN-Ban Tài chính kế toán",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "d422a45b-f867-4996-a98c-55e36ad65c52",
              text: "HN-Ban Quản trị nguồn lực",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "d6d0cd9b-fc62-45c8-88ac-c01a30896f9c",
              text: "HN-Ban Kinh doanh",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "f06d5057-13e7-45f3-9e15-95f05c276ce8",
              text: "HN-Ban An toàn môi trường",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "04201c0e-7ba0-46b0-9a6d-488a7693f43d",
              text: "HN-Ban Vận hành sản xuất",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
          ],
          li_attr: null,
          a_attr: null,
          left_paramvalues: null,
          left_iscount: false,
          left_paramnames: null,
        },
        {
          parentItem: null,
          id: "514aa4d7-a195-4142-8273-e574d7b97103",
          text: "Công ty CP công nghệ BTEC Chi nhánh Đà Nẵng",
          node_text: null,
          icon: null,
          state: null,
          children: [
            {
              parentItem: null,
              id: "95387054-22f0-4efe-a282-fb3073a52a89",
              text: "ĐN-Ban Công nghệ thông tin",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "b0ccb262-7566-475f-97af-01bd0aac2c0a",
              text: "ĐN-Ban Thương mại dịch vụ",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "4cb52fe3-e710-4fbf-82a4-e994b1f112e3",
              text: "ĐN-Ban Tài chính kế toán",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "4fedea46-50a4-4832-af24-d6bb1b6e26fd",
              text: "ĐN-Ban Vận hành sản xuất",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
          ],
          li_attr: null,
          a_attr: null,
          left_paramvalues: null,
          left_iscount: false,
          left_paramnames: null,
        },
        {
          parentItem: null,
          id: "e1541879-f592-473c-ad88-bc6f0197665c",
          text: "Công ty CP Nhựa Hoa Sen",
          node_text: null,
          icon: null,
          state: null,
          children: [
            {
              parentItem: null,
              id: "476bb0f3-e342-4cc6-a511-1267af2191a5",
              text: "CN1-Ban Giám đốc",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "c846afae-1617-46cb-9888-a2708cae108e",
              text: "CN1-Văn phòng",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "13c3fc50-e46f-4137-b104-13ae4ac4c238",
              text: "CN1-Ban Tài chính kế toán",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "946d2ff5-efb9-4a8e-93a2-10879fab2b0e",
              text: "CN1-Ban Thương mại dịch vụ",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
            {
              parentItem: null,
              id: "415d1601-733c-4a6e-ad80-252b0e2c4ab9",
              text: "CN1-Ban Công nghệ thông tin",
              node_text: null,
              icon: null,
              state: null,
              children: false,
              li_attr: null,
              a_attr: null,
              left_paramvalues: null,
              left_iscount: false,
              left_paramnames: null,
            },
          ],
          li_attr: null,
          a_attr: null,
          left_paramvalues: null,
          left_iscount: false,
          left_paramnames: null,
        },
      ];
      // Thay thế icon là null bằng một icon mặc định từ FontAwesome (hoặc từ một thư viện icon khác)
      const defaultIcon = "fa fa-sitemap"; // Icon mặc định nếu không có icon trong dữ liệu

      // Duyệt qua từng phần tử và thay thế icon nếu cần
      data.forEach((node) => {
        if (node.icon === null) {
          node.icon = defaultIcon; // Thêm icon mặc định vào các node có icon là null
        }
      });
      // Khởi tạo jsTree
      $(this.$refs.departmentTree).jstree({
        core: {
          data: data,
        },
        themes: {
          icons: true, // Bật tính năng icon
        },
      });
    },
    selectDepartments() {
      console.log("A department was selected!");
    },
  },
};
</script>

<style src="@/assets/css/departmentTree.css"></style>
